services:
  trade-ops-sentinel:
    image: ${TRADE_OPS_IMAGE:-ghcr.io/naoufalelbani/trade-ops-sentinel-freqtrade:v0.2.11}
    pull_policy: always
    container_name: trade-ops-sentinel
    restart: unless-stopped
    environment:
      HEARTBEAT_ALERT_ENABLED: ${HEARTBEAT_ALERT_ENABLED:-true}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - ft_userdata_default
    volumes:
      - ./data:/app/data

networks:
  ft_userdata_default:
    external: true
